# Generated by Django 5.1.4 on 2025-01-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pronat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronat_emri', models.CharField(blank=True, max_length=100, null=True)),
                ('pronat_pershkrimi', models.TextField(blank=True, max_length=1000, null=True)),
                ('pronat_imazhi', models.ImageField(blank=True, null=True, upload_to='pronat/')),
                ('pronat_cmimi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
