# Generated by Django 5.1.4 on 2025-01-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronat',
            name='pronat_cmimi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='pronat',
            name='pronat_pershkrimi',
            field=models.TextField(blank=True, max_length=1000000, null=True),
        ),
    ]
