# Generated by Django 5.1.4 on 2025-01-12 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacion', '0003_alter_pronat_pronat_cmimi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pronat',
            name='pronat_imazhi',
        ),
        migrations.CreateModel(
            name='PronatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pronat/')),
                ('pronat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Aplikacion.pronat')),
            ],
        ),
    ]
