# Generated by Django 5.1.4 on 2025-01-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacion', '0004_remove_pronat_pronat_imazhi_pronatimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronat',
            name='pronat_imazhi',
            field=models.ImageField(blank=True, null=True, upload_to='pronat/'),
        ),
        migrations.DeleteModel(
            name='PronatImage',
        ),
    ]
